version: "'{branch}-{build}'"
skip_non_tags: true
environment:
  PY_PYTHON: 3.7-32
install:
- cmd: >-
    set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

    python -m pip install -U pip

    pip install wheel

    pip install scons

    pip install markdown
build_script:
- cmd: scons
test_script:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG_NAME.StartsWith("v")) {
        Add-AppveyorMessage $env:APPVEYOR_REPO_TAG_NAME.substring(1)
    } else {
        Add-AppveyorMessage $env:APPVEYOR_REPO_TAG_NAME
    }
artifacts:
- path: '*.nvda-addon'
  name: addon
  type: WebDeployPackage
deploy:
- provider: Environment
  name: ftp_deployment
  on:
    APPVEYOR_REPO_TAG: true

notifications:
- provider: Email
  to:
  - adrianobarb@yahoo.it
  - abdelkrim.bensaid@free.fr
  - remyruiz@gmail.com
  subject: Download Weather_Plus{{#jobs}}{{#messages}}{{message}}{{/messages}}{{/jobs}}
  message: >-
    <h1>The add-on Weather_Plus{{#jobs}}{{#messages}}{{message}}{{/messages}}{{/jobs}} is ready!</h1>
         <p>You can download it from this link :</p>
         <p><a href="http://cyber25.free.fr/nvda-addons/Weather_Plus{{#jobs}}{{#messages}}{{message}}{{/messages}}{{/jobs}}.nvda-addon">Download Weather_Plus{{#jobs}}{{#messages}}{{message}}{{/messages}}{{/jobs}}.</a></p>
         <p>This email has been sent to you by appveyor.</p>
         <p>Best regards.</p>
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false